# Generated by Django 6.0.3 on 2026-03-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=100, verbose_name="Name of product"),
                ),
                (
                    "product_description",
                    models.TextField(verbose_name="Description of product"),
                ),
                (
                    "product_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Product price"
                    ),
                ),
                (
                    "deal_status",
                    models.CharField(
                        choices=[
                            ("PD", "PENDING"),
                            ("SH", "SHIPPED"),
                            ("Co", "COMPLETED"),
                            ("CA", "CANCELLED"),
                        ],
                        default="PD",
                        max_length=2,
                    ),
                ),
            ],
            options={
                "verbose_name": "Deal",
                "verbose_name_plural": "Deals",
            },
        ),
    ]
