# Generated by Django 6.0.3 on 2026-04-07 19:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_status",
            field=models.CharField(
                choices=[
                    ("PD", "PENDING"),
                    ("SH", "SHIPPED"),
                    ("CO", "COMPLETED"),
                    ("CA", "CANCELLED"),
                ],
                default="PD",
                max_length=2,
            ),
        ),
    ]
