# Generated by Django 6.0.3 on 2026-04-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0003_deal_created_at_deal_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="deal_status",
            field=models.CharField(
                choices=[
                    ("CR", "CREATED"),
                    ("PA", "PAID"),
                    ("SE", "SECURED"),
                    ("SH", "SHIPPED"),
                    ("DE", "DELIVERED"),
                    ("RE", "RELEASED"),
                    ("CA", "CANCELLED"),
                ],
                default="CR",
                max_length=2,
            ),
        ),
    ]
