# Generated by Django 6.0.3 on 2026-04-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0004_alter_deal_deal_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="buyer_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deal",
            name="seller_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_status",
            field=models.CharField(
                choices=[
                    ("CR", "CREATED"),
                    ("PA", "PAID"),
                    ("SE", "SECURED"),
                    ("SH", "SHIPPED"),
                    ("DE", "DELIVERED"),
                    ("RE", "RELEASED"),
                    ("CA", "CANCELLED"),
                    ("DI", "DISPUTED"),
                ],
                default="CR",
                max_length=2,
            ),
        ),
    ]
