# Generated by Django 6.0.3 on 2026-04-19 21:56

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


def fix_non_positive_prices(apps, schema_editor):
    Deal = apps.get_model('deals', 'Deal')
    for deal in Deal.objects.filter(product_price__lte=0):
        deal.product_price = Decimal('0.01')
        deal.save(update_fields=['product_price'])


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_deal_buyer_confirmed_deal_seller_confirmed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(fix_non_positive_prices, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(
                condition=models.Q(('product_price__gt', 0)),
                name='deal_product_price_positive',
            ),
        ),
    ]
