# Generated by Django 6.0.3 on 2026-03-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="User balance",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="escrow_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Escrow balance",
            ),
        ),
    ]
