# Generated by Django 6.0.3 on 2026-04-07 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_balance_alter_user_escrow_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="trust_score",
            field=models.DecimalField(
                decimal_places=1,
                default=5.0,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="Rating score of user",
            ),
        ),
    ]
